language: elixir
elixir:
  - 1.3.4
  - 1.4.0
  - 1.4.5
  - 1.5.0
otp_release:
  - 18.3
  - 19.2
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 20.0
    - elixir: 1.5.0
      otp_release: 20.0
    - elixir: 1.5.1
      otp_release: 20.0
sudo: false
env:
  - MIX_ENV=test
script:
  - mix espec
  - mix coveralls.travis
notifications:
  recipients:
    - dunyakirkali@gmail.com
    - onurkucukkece@gmail.com
